/**
 * GENERATED by `npm run contract:gen` — do not edit.
 * Source: api/openapi.yaml (sha256 97dbf1749d2be824)
 *
 * Types only, no runtime values: safe to import from CommonJS, ESM and under
 * Node's type stripper alike. Consumers alias what they need in ./index.ts.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for a bearer token */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Decoded JWT payload of the caller
         * @description Returns the token payload verbatim — not a user record.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All categories, ordered by name */
        get: operations["listCategories"];
        put?: never;
        /**
         * Create a category
         * @description **QUIRK** — `name` has no UNIQUE constraint, so this never conflicts and
         *     duplicates are created silently. Clients must dedupe by name themselves.
         *     (`seed.ts` uses `INSERT OR IGNORE`, which is therefore a no-op.)
         */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IntId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Replace a category
         * @description **QUIRK (B2)** — no required-field validation. Omitting `name` violates
         *     NOT NULL and surfaces as 500, not 400.
         */
        put: operations["updateCategory"];
        post?: never;
        /**
         * Delete a category
         * @description Hard delete. **QUIRK (B1)** — deleting a category referenced by a
         *     competition violates a foreign key and returns **500** with the raw SQLite
         *     message, not 409.
         */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/editions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All editions, newest year first */
        get: operations["listEditions"];
        put?: never;
        /**
         * Create an edition
         * @description Only `year` is persisted; other fields require a subsequent PUT. `year` is
         *     not validated as a calendar year — any integer is accepted.
         *
         *     This is the **only** endpoint that returns a clean 409 on duplication;
         *     competitions return 500 for the analogous case (see `createCompetition`).
         */
        post: operations["createEdition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/editions/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Editions are keyed by year; there is no separate id. */
                year: components["parameters"]["Year"];
            };
            cookie?: never;
        };
        /** Get an edition by year */
        get: operations["getEdition"];
        /**
         * Replace an edition
         * @description **QUIRK (C1)** — every omitted field is written as NULL. This is a full
         *     replace, not a merge: sending only `committee` wipes `presenters`.
         *     `year` itself cannot be changed. There is no DELETE for editions (B9).
         */
        put: operations["updateEdition"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/editions/{year}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Editions are keyed by year; there is no separate id. */
                year: components["parameters"]["Year"];
            };
            cookie?: never;
        };
        /**
         * List an edition's uploads
         * @description Returns `[]` for an unknown year rather than 404.
         */
        get: operations["listEditionUploads"];
        put?: never;
        /**
         * Attach an upload to an edition
         * @description **QUIRK (B1)** — the edition is not checked to exist; a bad year violates a
         *     foreign key and returns 500.
         */
        post: operations["createEditionUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List competitions
         * @description Ordered `rank ASC, id ASC` — clients rely on this (bythfod's running order).
         *     Inner-joins `category`, so a competition with a dangling `category_id`
         *     would be omitted entirely.
         */
        get: operations["listCompetitions"];
        put?: never;
        /**
         * Create a competition
         * @description `id` is supplied by the caller — it is a TEXT primary key, not generated.
         *
         *     **QUIRK (B1)** — a duplicate `id` violates the primary key and returns
         *     **500** with the raw SQLite message, where the analogous edition case
         *     returns a clean 409. **QUIRK (B2)** — `language` and `type` are validated
         *     only by SQL CHECK, so an invalid value is a 500, not a 400.
         *
         *     The response is the inserted row **without** the category JOIN, so
         *     `category_name` is absent here but present on GET.
         */
        post: operations["createCompetition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["StringId"];
            };
            cookie?: never;
        };
        /** Get a competition */
        get: operations["getCompetition"];
        /**
         * Replace a competition
         * @description **QUIRK (C6)** — `year` and `id` are silently not updatable; they are
         *     omitted from the SET clause. **QUIRK (C1)** — omitted fields become NULL.
         *     Response has no category JOIN.
         */
        put: operations["updateCompetition"];
        post?: never;
        /**
         * Delete a competition
         * @description Hard delete, no cascade. **QUIRK (B1)** — a competition with registrations
         *     or works violates a foreign key and returns **500**. Note that dropping a
         *     registration is a soft delete, so the row still exists and still blocks
         *     deletion.
         */
        delete: operations["deleteCompetition"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List or search participants
         * @description Ordered `surname ASC, name ASC`.
         *
         *     **QUIRK (B3)** — soft-deleted participants (`active = 0`) are **still
         *     returned**; there is no `active` filter. Clients must filter themselves.
         */
        get: operations["listParticipants"];
        put?: never;
        /**
         * Create a participant
         * @description `active` defaults to 1 when omitted. `type` is validated only by SQL CHECK (B2).
         */
        post: operations["createParticipant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IntId"];
            };
            cookie?: never;
        };
        /**
         * Get a participant
         * @description **QUIRK (B3)** — returns inactive participants too.
         */
        get: operations["getParticipant"];
        /**
         * Replace a participant
         * @description Omitting `active` preserves the current value (unlike POST, which defaults
         *     it to 1). **QUIRK (C1)** — other omitted fields become NULL.
         */
        put: operations["updateParticipant"];
        post?: never;
        /**
         * Deactivate a participant
         * @description **Soft delete** — sets `active = 0`; the row remains and is still returned
         *     by the list endpoints (B3). Repeating the call on an already-inactive
         *     participant still reports a change and still returns 204, so callers
         *     cannot tell "deleted" from "already deleted".
         */
        delete: operations["deleteParticipant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List registrations
         * @description Ordered `surname ASC, name ASC`. **Dropped registrations are always
         *     excluded** — `dropped = 0` is hardcoded with no way to include them (B4).
         *     Joins participant and competition, so the response carries read-only
         *     fields absent from the single-item form (see `getRegistration`).
         */
        get: operations["listRegistrations"];
        put?: never;
        /**
         * Register a participant
         * @description `registered_at` is server-generated and cannot be set. **QUIRK (B5)** — no
         *     uniqueness check: the same participant can be registered twice for the
         *     same competition.
         */
        post: operations["createRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registrations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IntId"];
            };
            cookie?: never;
        };
        /**
         * Get a registration
         * @description **QUIRK (A8)** — a narrower shape than the list endpoint: joins only
         *     `name` and `surname`, omitting `type`, `comp_description` and `language`.
         *     Also does **not** filter `dropped`, so a dropped registration is still
         *     fetchable here while being invisible in the list.
         */
        get: operations["getRegistration"];
        /**
         * Update a registration
         * @description Only `competition_id` and `pseudonym` are updatable; `participant_id` and `year` are fixed at creation.
         */
        put: operations["updateRegistration"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registrations/{id}/drop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IntId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Withdraw a registration (soft delete)
         * @description Sets `dropped = 1`. Takes no request body.
         *
         *     **QUIRK (B6)** — returns `200` with `{ message }` where every sibling
         *     mutation returns `204`. There is no hard DELETE for registrations (B9),
         *     so this is the only removal path and the row persists forever.
         */
        patch: operations["dropRegistration"];
        trace?: never;
    };
    "/works": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List works
         * @description Ordered `placement ASC, title ASC`. `placement` is TEXT, so this sorts
         *     lexicographically and NULLs come first.
         */
        get: operations["listWorks"];
        put?: never;
        /**
         * Record a work
         * @description `date` is server-generated; a `date` in the body is ignored. `placement` is
         *     validated only by SQL CHECK (B2). No uniqueness constraint — posting the
         *     same body twice creates two rows, which matters for clients that retry.
         */
        post: operations["createWork"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/works/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IntId"];
            };
            cookie?: never;
        };
        /**
         * Get a work
         * @description **QUIRK (A8)** — joins only `name`/`surname`, omitting `type` which the list endpoint includes.
         */
        get: operations["getWork"];
        /**
         * Update a work
         * @description `participant_id`, `competition_id` and `date` are not updatable. **QUIRK (C1)** — omitted fields become NULL.
         */
        put: operations["updateWork"];
        post?: never;
        /**
         * Delete a work
         * @description Hard delete — works are the one entity that genuinely disappears.
         */
        delete: operations["deleteWork"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        LoginResponse: {
            token: string;
            name: string | null;
            username: string;
        };
        JwtPayload: {
            userId: number;
            username: string;
        };
        /**
         * @description IND = individual, GRU = group. Shared by participants and competitions.
         * @enum {string}
         */
        EntrantType: "IND" | "GRU";
        /**
         * @description Null means no placement awarded (or not yet adjudicated).
         * @enum {string|null}
         */
        Placement: "1" | "2" | "3" | "mencion" | null;
        /**
         * @description Enforced by SQL CHECK. Note the values carry no diacritics (`Aleman`,
         *     not `Alemán`).
         * @enum {string|null}
         */
        Language: "Cymraeg" | "Castellano" | "English" | "Aleman" | "Polaco" | "Frances" | "Portugues" | "Italiano" | "Otro" | null;
        CategoryInput: {
            name: string;
            name_welsh?: string | null;
        };
        Category: {
            id: number;
            name: string;
            name_welsh?: string | null;
        };
        EditionInput: {
            committee?: string | null;
            committee_img?: string | null;
            presenters?: string | null;
            presenters_img?: string | null;
        };
        Edition: {
            year: number;
            committee?: string | null;
            committee_img?: string | null;
            presenters?: string | null;
            presenters_img?: string | null;
        };
        Upload: {
            id: number;
            year: number;
            filename: string;
            description?: string | null;
        };
        CompetitionInput: {
            /** @description Caller-supplied primary key. */
            id: string;
            category_id: number;
            year: number;
            type: components["schemas"]["EntrantType"];
            description?: string | null;
            language?: components["schemas"]["Language"];
            extra_text?: string | null;
            /** @description Defaults to 0 when omitted. */
            rank?: number;
            preliminary?: string | null;
        };
        /** @description `id` and `year` are ignored if sent. */
        CompetitionUpdate: {
            category_id?: number;
            type?: components["schemas"]["EntrantType"];
            description?: string | null;
            language?: components["schemas"]["Language"];
            extra_text?: string | null;
            rank?: number | null;
            preliminary?: string | null;
        };
        /** @description The stored row, as returned by POST and PUT (no category JOIN). */
        CompetitionRow: {
            id: string;
            category_id: number;
            year: number;
            type: components["schemas"]["EntrantType"];
            description?: string | null;
            language?: components["schemas"]["Language"];
            extra_text?: string | null;
            rank?: number | null;
            preliminary?: string | null;
        };
        Competition: components["schemas"]["CompetitionRow"] & {
            readonly category_name?: string | null;
            readonly category_name_welsh?: string | null;
        };
        ParticipantInput: {
            name: string;
            type: components["schemas"]["EntrantType"];
            surname?: string | null;
            document_id?: string | null;
            birth_date?: string | null;
            nationality?: string | null;
            residence?: string | null;
            email?: string | null;
            phone?: string | null;
            /** @description Accepts boolean, number or string; coerced to 0/1. */
            active?: (0 | 1) | boolean | string;
        };
        Participant: {
            id: number;
            name: string;
            type: components["schemas"]["EntrantType"];
            surname?: string | null;
            document_id?: string | null;
            birth_date?: string | null;
            nationality?: string | null;
            residence?: string | null;
            email?: string | null;
            phone?: string | null;
            /** @enum {integer} */
            active: 0 | 1;
        };
        RegistrationInput: {
            participant_id: number;
            competition_id: string;
            year: number;
            pseudonym?: string | null;
        };
        /** @description The stored row, as returned by POST and PUT. */
        Registration: {
            id: number;
            participant_id: number;
            competition_id: string;
            year: number;
            pseudonym?: string | null;
            readonly registered_at?: string | null;
            /** @enum {integer} */
            dropped: 0 | 1;
        };
        RegistrationItem: components["schemas"]["Registration"] & {
            readonly name?: string | null;
            readonly surname?: string | null;
        };
        RegistrationListItem: components["schemas"]["RegistrationItem"] & {
            type?: components["schemas"]["EntrantType"];
            readonly comp_description?: string | null;
            language?: components["schemas"]["Language"];
        };
        WorkInput: {
            participant_id: number;
            competition_id: string;
            title: string;
            display_name?: string | null;
            placement?: components["schemas"]["Placement"];
            video_url?: string | null;
            photo_url?: string | null;
        };
        WorkUpdate: {
            title?: string;
            display_name?: string | null;
            placement?: components["schemas"]["Placement"];
            video_url?: string | null;
            photo_url?: string | null;
        };
        Work: {
            id: number;
            participant_id: number;
            competition_id: string;
            title: string;
            display_name?: string | null;
            placement?: components["schemas"]["Placement"];
            readonly date?: string | null;
            video_url?: string | null;
            photo_url?: string | null;
        };
        WorkItem: components["schemas"]["Work"] & {
            readonly name?: string | null;
            readonly surname?: string | null;
        };
        WorkListItem: components["schemas"]["WorkItem"] & {
            type?: components["schemas"]["EntrantType"];
        };
    };
    responses: {
        /**
         * @description `{ error: "Token requerido" }` when the header is missing or malformed,
         *     `{ error: "Token inválido o expirado" }` when verification fails.
         *     **QUIRK (A4)** — these are Spanish while most other errors are English.
         */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `{ error: "<Entity> not found" }` */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description **QUIRK (B1/B8)** — a database constraint violation (foreign key, unique,
         *     NOT NULL, CHECK) is not mapped to a status code. It reaches the generic
         *     error handler and is returned as **500 with the raw SQLite message**,
         *     e.g. `{ error: "FOREIGN KEY constraint failed" }`. Semantically these are
         *     409 or 400; treat any 500 here as a constraint failure, not an outage.
         */
        ConstraintAs500: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        IntId: number;
        StringId: string;
        /** @description Editions are keyed by year; there is no separate id. */
        Year: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Token issued. Expiry follows JWT_EXPIRES_IN (default 8h). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description `{ error: "username and password are required" }` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description `{ error: "Invalid credentials" }` — English, unlike the middleware's Spanish 401s. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JwtPayload"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            /** @description `{ error: "name is required" }` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IntId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ConstraintAs500"];
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IntId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ConstraintAs500"];
        };
    };
    listEditions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Edition"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createEdition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    year: number;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Edition"];
                };
            };
            /** @description `{ error: "year is required" }` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description `{ error: "Edition already exists" }` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getEdition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Editions are keyed by year; there is no separate id. */
                year: components["parameters"]["Year"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Edition"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateEdition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Editions are keyed by year; there is no separate id. */
                year: components["parameters"]["Year"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditionInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Edition"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listEditionUploads: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Editions are keyed by year; there is no separate id. */
                year: components["parameters"]["Year"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Upload"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createEditionUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Editions are keyed by year; there is no separate id. */
                year: components["parameters"]["Year"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    filename: string;
                    description?: string | null;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Upload"];
                };
            };
            /** @description `{ error: "filename is required" }` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["ConstraintAs500"];
        };
    };
    listCompetitions: {
        parameters: {
            query?: {
                /** @description Exact match */
                year?: number;
                type?: components["schemas"]["EntrantType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createCompetition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitionInput"];
            };
        };
        responses: {
            /** @description Created (no category JOIN) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionRow"];
                };
            };
            /** @description `{ error: "id, category_id, year, and type are required" }` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["ConstraintAs500"];
        };
    };
    getCompetition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["StringId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCompetition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["StringId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitionUpdate"];
            };
        };
        responses: {
            /** @description Updated (no category JOIN) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionRow"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ConstraintAs500"];
        };
    };
    deleteCompetition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["StringId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ConstraintAs500"];
        };
    };
    listParticipants: {
        parameters: {
            query?: {
                type?: components["schemas"]["EntrantType"];
                /**
                 * @description Substring match — `LIKE '%q%'` across **name, surname AND document_id**.
                 *     Case-insensitive for ASCII. A search for `SIM-` therefore also matches
                 *     a person named "Simón"; callers must re-check the field they meant.
                 */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participant"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createParticipant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParticipantInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participant"];
                };
            };
            /** @description `{ error: "name and type are required" }` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["ConstraintAs500"];
        };
    };
    getParticipant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IntId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participant"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateParticipant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IntId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParticipantInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participant"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ConstraintAs500"];
        };
    };
    deleteParticipant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IntId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Marked inactive */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listRegistrations: {
        parameters: {
            query?: {
                year?: number;
                comp?: string;
                participant?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationListItem"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Registration"];
                };
            };
            /** @description `{ error: "participant_id, competition_id, and year are required" }` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["ConstraintAs500"];
        };
    };
    getRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IntId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationItem"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IntId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    competition_id?: string;
                    pseudonym?: string | null;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Registration"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    dropRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IntId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `{ message: "Registration dropped" }` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listWorks: {
        parameters: {
            query?: {
                comp?: string;
                participant?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkListItem"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createWork: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Work"];
                };
            };
            /** @description `{ error: "participant_id, competition_id, and title are required" }` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["ConstraintAs500"];
        };
    };
    getWork: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IntId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItem"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateWork: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IntId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Work"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ConstraintAs500"];
        };
    };
    deleteWork: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IntId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
