#!/usr/bin/env node
/**
 * Generates TypeScript types from openapi.yaml for every consumer.
 *
 * The generated files are COMMITTED, not built on demand: bythfod is a separate
 * repo and cannot reach this node_modules, the Angular Pages deploy must not gain
 * a codegen step, and `git diff` then shows contract changes in review.
 *
 * Critical invariant: the output must contain no VALUE exports — only types.
 * That is what lets one file compile unchanged under the API's CommonJS/ES2020,
 * the app's ESM/ES2022 bundler resolution, and Node's type stripper in bythfod.
 * Enforced below; the script fails rather than emit something unshareable.
 *
 * Usage:  node scripts/gen-types.mjs [--check]
 *   --check  regenerate into a temp file and fail if the committed copy differs
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const apiDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = resolve(apiDir, '..');
const spec = join(apiDir, 'openapi.yaml');
const check = process.argv.includes('--check');

/** Where the generated types land, per consumer. */
const TARGETS = [
  { name: 'api', path: join(apiDir, 'src/types/api.generated.ts') },
  { name: 'app', path: join(repoRoot, 'app/src/app/core/models/api.generated.ts') },
];

const BANNER = (hash) => `/**
 * GENERATED by \`npm run contract:gen\` — do not edit.
 * Source: api/openapi.yaml (sha256 ${hash})
 *
 * Types only, no runtime values: safe to import from CommonJS, ESM and under
 * Node's type stripper alike. Consumers alias what they need in ./index.ts.
 */
`;


const { createHash } = await import('node:crypto');
const hash = createHash('sha256').update(readFileSync(spec)).digest('hex').slice(0, 16);

const raw = execFileSync(
  'npx',
  ['openapi-typescript', spec, '--empty-objects-unknown'],
  { cwd: apiDir, encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 },
);

// Guard the invariant that makes this file shareable across module systems.
const valueExport = raw.match(/^export\s+(?!type\b|interface\b)(\w+)/m);
if (valueExport) {
  console.error(`✘ generated output contains a value export (${valueExport[1]}).`);
  console.error('  That would break sharing across CommonJS/ESM/type-stripping.');
  process.exit(1);
}

const content = BANNER(hash) + raw;

let failed = false;
for (const t of TARGETS) {
  if (check) {
    if (!existsSync(t.path)) { console.error(`✘ ${t.name}: ${t.path} is missing`); failed = true; continue; }
    const current = readFileSync(t.path, 'utf8');
    if (current !== content) {
      console.error(`✘ ${t.name}: generated types are stale — run \`npm run contract:gen\``);
      failed = true;
    } else {
      console.log(`✔ ${t.name}: up to date`);
    }
  } else {
    mkdirSync(dirname(t.path), { recursive: true });
    writeFileSync(t.path, content);
    console.log(`✔ ${t.name}: wrote ${t.path.replace(repoRoot + '/', '')}`);
  }
}

if (failed) process.exit(1);
if (!check) console.log(`  spec sha256 ${hash} · ${content.split('\n').length} lines`);
